title: advantAGE Seniors
description: Advantage seniors is an elder care specialist in bangalore that offers elderly home, senior home care, care for elderly parents, and geriatrics.
url: https://seniorcare.icsoln.com
alt: senior care, coma care, carehome, elder care
destination: public
permalink: /:title/

contact-email-link: "mailto:advantagejacob@gmail.com"
contact-phone-number: "09844495527"

sass:
  sass_dir: /assets/css/_sass
  style: compressed


include:
  - _pages

# collections:
#   lionels-world:
#     output: true
#     permalink: /lionels-world/:path/
#
collections:
  illustrations:
    output: true

paginate: 4
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

facebook:
  app_id: 580865736041893
  publisher: "advantAGE Seniors"

twitter:
  username: AdvantageSenio4
  card: summary
