title: advantAGE Seniors
description: Are you looking for a place to keep your loved one?
url: http://advantageseniors.org
alt: senior care, coma care, carehome, elder care
destination: public
permalink: /:title/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages


collections:
  lionels-world:
    output: true
    permalink: /lionels-world/:path/

paginate: 4
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

facebook:
  app_id: 580865736041893
  publisher: "advantAGE Seniors"

twitter:
  username: AdvantageSenio4
  card: summary