title: advantAGE Seniors
description: Are you looking for a place to keep your loved one?
url: http://advantageseniors.org
alt: senior care, coma care, carehome, elder care
destination: public

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

paginate: 4
paginate_path: "/blog/page:num/"
#permalink: /blog/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
